spring.application.name=project

# ========================
# SERVER
# ========================
server.port=${PORT:8080}

# ========================
# DATABASE (Railway MySQL)
# ========================
spring.datasource.url=jdbc:mysql://shinkansen.proxy.rlwy.net:42592/railway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=negcfPQjoKKapGEEAyzveFwxQeeQxXnu
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ========================
# HIKARI POOL
# ========================
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=30000

# ========================
# JPA / HIBERNATE
# ========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ========================
# JWT
# ========================
app.jwt.secret=PathfinderSuperSecretKeyForJWTtokenGeneration2024MustBeAtLeast256BitsLong!!
app.jwt.expiration-ms=86400000

# ========================
# SWAGGER
# ========================
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# ========================
# CORS
# ========================
app.cors.allowed-origins=http://localhost:5173,http://localhost:3000,https://yourfrontend.up.railway.app
